[steam]
prefix_dir=
prefix_select=newest

[proton]
dir=
select=newest

[interactive]
ui=wizard

[instances]
mode=split
# mode=single
# game_prefix=
# edcopilot_prefix=
# tool_prefix_base=

[shared_data]
enabled=true
source_prefix=game
strategy=symlink

[paths]
mined_native=
mined_exe=MinEdLauncher.exe
edcopilot_exe=LaunchEDCoPilot.exe

[performance]
pulse_latency_msec=90
dxvk_filter_device_name=RTX 3060
dxvk_frame_rate=60
prefer_nvidia_icd=auto
